从网络安装command

diff --git a/yxct b/yxct
--- a/yxct
+++ b/yxct
@@ -2719,39 +2719,64 @@ function cmd_install()
 
     # 如果未提供'script_path'
     if [ -z "${script_path}" ]; then
-      
-      # 如果使用了 --cache 参数
-      if ${use_cache}; then
+
+      # get a valid cache path
+      # 如果 '--cache' 参数未提供 path
+      if [ -z "${cache_path}" ]; then
         
-        # 如果 '--cache' 参数未提供 path
-        if [ -z "${cache_path}" ]; then
-          
-          if [ -n "${YXCT_CACHE_PATH}" ]; then
-            # 如果提供了环境变量， 从环境变量中读取 cache 路径
-            # 环境变量中的 cache路径必须存在
-            cache_path="${YXCT_CACHE_PATH}"
-            if ! [ -e "${cache_path}" ]; then
-              yxct_fatal "${cache_path} not exist"
-            fi
-          else
-            # 如果没提供环境变量，使用默认cache路径.
-            # 默认 cache 路径可能是空的或者未创建, 则说明未找到命令
-            cache_path="$(yxct_get_default_cache_path)"
-            if ! [ -d "${cache_path}" ]; then
-              yxct_fatal "can not find command ${command} from cache"
-            fi
+        if [ -n "${YXCT_CACHE_PATH}" ]; then
+          # 如果提供了环境变量， 从环境变量中读取 cache 路径
+          # 环境变量中的 cache路径必须存在
+          cache_path="${YXCT_CACHE_PATH}"
+          if ! [ -e "${cache_path}" ]; then
+            yxct_fatal "${cache_path} not exist"
+          fi
+        else
+          # 如果没提供环境变量，使用默认cache路径.
+          # 默认 cache 路径可能是空的或者未创建, 则说明未找到命令
+          cache_path="$(yxct_get_default_cache_path)"
+          if ! [ -d "${cache_path}" ]; then
+            yxct_fatal "can not find command ${command} from cache"
           fi
         fi
+      fi
 
-        # 在cache中搜索命令安装包，并更新script_path
-        script_path=$(search_in_cache "${command}" "${cache_path}")
-        if [ -z "${script_path}" ]; then
-          yxct_fatal "can not find command ${command} from cache"
+      # 如果没指定 --cache 参数， 那么准备好 cache
+      if ! ${use_cache}; then
+        # update index
+        if ! update_index_if_need; then
+          yxct_fatal "failed to update index"
         fi
 
-      else
-        yxct_fatal "Script path is empty. Use --help to show more information."
-      fi # end of (if ${use_cache}; then)
+        if ! checkout_a_cache "${command}"; then
+          yxct_fatal "failed to checkout '${command}'"
+        fi
+      fi
+
+      # 在cache中搜索命令安装包，并更新script_path
+      script_path=$(search_in_cache "${command}" "${cache_path}")
+      if [ -z "${script_path}" ]; then
+        yxct_fatal "can not find command ${command} from cache"
+      fi
+      
+      # # 如果使用了 --cache 参数
+      # if ${use_cache}; then
+        
+      #   # 在cache中搜索命令安装包，并更新script_path
+      #   script_path=$(search_in_cache "${command}" "${cache_path}")
+      #   if [ -z "${script_path}" ]; then
+      #     yxct_fatal "can not find command ${command} from cache"
+      #   fi
+
+      # else
+      #   if ! update_index_if_need; then
+      #     yxct_fatal "failed to update index"
+      #   fi
+
+      #   checkout_a_cache "${command}"
+      #   # exit 0
+      #   yxct_fatal "Script path is empty. Use --help to show more information."
+      # fi # end of (if ${use_cache}; then)
     fi
 
 
